language: java
jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11     # LTS
  - oraclejdk11
sudo: true
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
after_success:
  - bash <(curl -s https://codecov.io/bash)